/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7p2_cesarnunez_12141019;

import javax.swing.JOptionPane;


public class Main extends javax.swing.JFrame {

    private AdministrarEquipo ae = new AdministrarEquipo("./equipos.txt");
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_equipo = new javax.swing.JMenu();
        jmi_crear = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_cargar = new javax.swing.JMenuItem();
        jm_partidos = new javax.swing.JMenu();
        jmi_simular = new javax.swing.JMenuItem();
        jmi_tablaPosiciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setText("Torneo Local");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 440, 248));

        jm_equipo.setText("Equipo");

        jmi_crear.setText("Crear");
        jmi_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearActionPerformed(evt);
            }
        });
        jm_equipo.add(jmi_crear);

        jmi_modificar.setText("Modificar");
        jm_equipo.add(jmi_modificar);

        jmi_eliminar.setText("Eliminar");
        jm_equipo.add(jmi_eliminar);

        jmi_cargar.setText("Cargar Archivo");
        jm_equipo.add(jmi_cargar);

        jMenuBar1.add(jm_equipo);

        jm_partidos.setText("Partidos");

        jmi_simular.setText("Simular");
        jm_partidos.add(jmi_simular);

        jmi_tablaPosiciones.setText("jMenuItem1");
        jm_partidos.add(jmi_tablaPosiciones);

        jMenuBar1.add(jm_partidos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearActionPerformed
        String nombre = JOptionPane.showInputDialog("Nombre del equipo: ");
        try{
            ae.cargarArchivo();
            ae.setEquipo(new Equipo(nombre));
            ae.escribirArchivo();            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, no se pudo crear el equipo!");
        }        
    }//GEN-LAST:event_jmi_crearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jm_equipo;
    private javax.swing.JMenu jm_partidos;
    private javax.swing.JMenuItem jmi_cargar;
    private javax.swing.JMenuItem jmi_crear;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_modificar;
    private javax.swing.JMenuItem jmi_simular;
    private javax.swing.JMenuItem jmi_tablaPosiciones;
    // End of variables declaration//GEN-END:variables
}
